CREATE SCHEMA IF NOT EXISTS portfolio;

CREATE TABLE portfolio.portfolio
(
    id         int8 GENERATED BY DEFAULT AS IDENTITY (INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    name       varchar(50)                                                                                                             NOT NULL,
    user_id    int8                                                                                                                    NOT NULL,
    is_default boolean                                                                                                                 NOT NULL,
    CONSTRAINT portfolio_pkey PRIMARY KEY (id)
);

CREATE TABLE portfolio.owned_stock
(
    id             int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_id   int8                                  NOT NULL,
    ticker         varchar(10)                           NOT NULL,
    quantity       int4                                  NOT NULL,
    purchase_price numeric(19, 2)                        NOT NULL,
    CONSTRAINT owned_stock_pkey PRIMARY KEY (id),
    CONSTRAINT fk_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolio.portfolio (id)
);

CREATE TABLE portfolio.watchlist
(
    id           int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    portfolio_id int8                                  NOT NULL,
    ticker       varchar(10)                           NOT NULL,
    CONSTRAINT watchlist_pkey PRIMARY KEY (id),
    CONSTRAINT fk_watchlist_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolio.portfolio (id)
);

INSERT INTO portfolio.portfolio (user_id, name, is_default)
VALUES (101, 'My first portfolio', true),
       (102, 'ETF Portfolio', true),
       (103, 'Index Funds', true);

INSERT INTO portfolio.owned_stock (portfolio_id, ticker, quantity, purchase_price)
VALUES (1, 'MSFT', 10, 399.99),
       (1, 'EBAY', 25, 90.25),
       (1, 'AAPL', 20, 287.00),
       (2, 'DRUM', 10, 101.05),
       (2, 'HOOD', 10, 144.75),
       (3, 'CHASE', 10, 93.67);

INSERT INTO portfolio.watchlist (portfolio_id, ticker)
VALUES (1, 'QQQ'),
       (1, 'VOO'),
       (1, 'VXUS'),
       (1, 'ARKK'),
       (1, 'ORCL'),
       (2, 'NOW'),
       (2, 'NVDA'),
       (3, 'AMD'),
       (3, 'TSLA'),
       (3, 'AMZN'),
       (3, 'VOOG');
